// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;
using OneTradeCentral.DTOs;

namespace OneTradeCentral.iOS
{
	public partial class UOMViewController : UIViewController
	{

		static IList<UOM> uomList = new List<UOM> ();

		private OrderLineViewController _olineViewController;

		public OrderLineViewController OrderLineController { get{ return _olineViewController;} set{ _olineViewController = value;} }

		public UOMViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();

			DALFacade dal = new DALFacade ();

			uomList = dal.getUOMList ();

			UOMPickerView.Model = new UOMPickerModel (_olineViewController);
		}

		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);
			if (uomList.Count > 0) {
				OrderLineController.SelectUOM (uomList [0]);
			}
		}


		public class UOMPickerModel : UIPickerViewModel
		{
			public OrderLineViewController _orderLineViewController;

			public UOMPickerModel(OrderLineViewController _olController) {
				_orderLineViewController = _olController;
			}

			public override nint GetComponentCount (UIPickerView picker)
			{
				return 1;
			}

			public override string GetTitle (UIPickerView picker, nint row, nint component)
			{
				return uomList[(int)row].Name;
			}

			public override nint GetRowsInComponent (UIPickerView picker, nint component)
			{
				return uomList.Count;
			}

			public override void Selected (UIPickerView picker, nint row, nint component)
			{

				_orderLineViewController.SelectUOM (uomList [(int)row]);
								
			}
		}
	}





}
