// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OneTradeCentral.iOS.OrdersWebService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    using System.Data;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="mobileservicesSoap", Namespace="http://4solutions.co.au/")]
    public partial class mobileservices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// CodeRemarks
        public mobileservices() {
            this.Url = "https://testwsorder.orderlinc.com/mobileservices.asmx";
        }
        
        public mobileservices(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/IsOnline", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsOnline() {
            object[] results = this.Invoke("IsOnline", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginIsOnline(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsOnline", new object[0], callback, asyncState);
        }
        
        /// CodeRemarks
        public bool EndIsOnline(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/EmailNotification", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EmailNotification(string Email, out string ErrorMessage) {
            object[] results = this.Invoke("EmailNotification", new object[] {
                        Email});
            ErrorMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginEmailNotification(string Email, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("EmailNotification", new object[] {
                        Email}, callback, asyncState);
        }
        
        /// CodeRemarks
        public bool EndEmailNotification(System.IAsyncResult asyncResult, out string ErrorMessage) {
            object[] results = this.EndInvoke(asyncResult);
            ErrorMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/VersionControl", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool VersionControl(string VersionMajor, string VersionMinor, out string ErroMessage) {
            object[] results = this.Invoke("VersionControl", new object[] {
                        VersionMajor,
                        VersionMinor});
            ErroMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginVersionControl(string VersionMajor, string VersionMinor, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("VersionControl", new object[] {
                        VersionMajor,
                        VersionMinor}, callback, asyncState);
        }
        
        /// CodeRemarks
        public bool EndVersionControl(System.IAsyncResult asyncResult, out string ErroMessage) {
            object[] results = this.EndInvoke(asyncResult);
            ErroMessage = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/GetReferenceData", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetReferenceData(long salesOrgNo, long repAccountNo, string mOrderLincVersion, string mIOSVersion) {
            object[] results = this.Invoke("GetReferenceData", new object[] {
                        salesOrgNo,
                        repAccountNo,
                        mOrderLincVersion,
                        mIOSVersion});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginGetReferenceData(long salesOrgNo, long repAccountNo, string mOrderLincVersion, string mIOSVersion, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetReferenceData", new object[] {
                        salesOrgNo,
                        repAccountNo,
                        mOrderLincVersion,
                        mIOSVersion}, callback, asyncState);
        }
        
        /// CodeRemarks
        public System.Data.DataSet EndGetReferenceData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/SubmitOrder", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long SubmitOrder(DTOOrder order, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] imageArray, DTOContact contact, string uName, string uPW, string deviceNo, out string ServerMessage) {
            object[] results = this.Invoke("SubmitOrder", new object[] {
                        order,
                        imageArray,
                        contact,
                        uName,
                        uPW,
                        deviceNo});
            ServerMessage = ((string)(results[1]));
            return ((long)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginSubmitOrder(DTOOrder order, byte[] imageArray, DTOContact contact, string uName, string uPW, string deviceNo, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SubmitOrder", new object[] {
                        order,
                        imageArray,
                        contact,
                        uName,
                        uPW,
                        deviceNo}, callback, asyncState);
        }
        
        /// CodeRemarks
        public long EndSubmitOrder(System.IAsyncResult asyncResult, out string ServerMessage) {
            object[] results = this.EndInvoke(asyncResult);
            ServerMessage = ((string)(results[1]));
            return ((long)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/CreateError", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateError() {
            object[] results = this.Invoke("CreateError", new object[0]);
            return ((int)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginCreateError(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateError", new object[0], callback, asyncState);
        }
        
        /// CodeRemarks
        public int EndCreateError(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://4solutions.co.au/LastReleaseDate", RequestNamespace="http://4solutions.co.au/", ResponseNamespace="http://4solutions.co.au/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LastReleaseDate() {
            object[] results = this.Invoke("LastReleaseDate", new object[0]);
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginLastReleaseDate(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LastReleaseDate", new object[0], callback, asyncState);
        }
        
        /// CodeRemarks
        public string EndLastReleaseDate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://4solutions.co.au/")]
    public partial class DTOOrder {
        
        /// <remarks/>
        public long OrderID;
        
        /// <remarks/>
        public long SalesOrgID;
        
        /// <remarks/>
        public long CustomerID;
        
        /// <remarks/>
        public long SalesRepAccountID;
        
        /// <remarks/>
        public long ProviderID;
        
        /// <remarks/>
        public int ProviderWarehouseID;
        
        /// <remarks/>
        public System.DateTime OrderDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DeliveryDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> InvoiceDate;
        
        /// <remarks/>
        public int SYSOrderStatusID;
        
        /// <remarks/>
        public string OrderNumber;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReceivedDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ReleaseDate;
        
        /// <remarks/>
        public bool IsSent;
        
        /// <remarks/>
        public bool IsHeld;
        
        /// <remarks/>
        public System.DateTime DateCreated;
        
        /// <remarks/>
        public System.DateTime DateUpdated;
        
        /// <remarks/>
        public long CreatedByUserID;
        
        /// <remarks/>
        public long UpdatedByUserID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> HoldUntilDate;
        
        /// <remarks/>
        public bool IsMobile;
        
        /// <remarks/>
        public string OrderGUID;
        
        /// <remarks/>
        public string ProviderCustomerCode;
        
        /// <remarks/>
        public DTOOrderLine[] OrderLine;
        
        /// <remarks/>
        public string SYSOrderStatusText;
        
        /// <remarks/>
        public string CustomerName;
        
        /// <remarks/>
        public string ProviderName;
        
        /// <remarks/>
        public string CreatedByName;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> IsRegularOrder;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> RequestedReleaseDate;
        
        /// <remarks/>
        public string PONumber;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://4solutions.co.au/")]
    public partial class DTOOrderLine {
        
        /// <remarks/>
        public long OrderLineID;
        
        /// <remarks/>
        public long OrderID;
        
        /// <remarks/>
        public int LineNum;
        
        /// <remarks/>
        public long ProductID;
        
        /// <remarks/>
        public float OrderQty;
        
        /// <remarks/>
        public float DespatchQty;
        
        /// <remarks/>
        public string UOM;
        
        /// <remarks/>
        public float OrderPrice;
        
        /// <remarks/>
        public float DespatchPrice;
        
        /// <remarks/>
        public string ItemStatus;
        
        /// <remarks/>
        public string ErrorText;
        
        /// <remarks/>
        public float Discount;
        
        /// <remarks/>
        public string ProductCode;
        
        /// <remarks/>
        public string PrimarySKU;
        
        /// <remarks/>
        public string ProductName;
        
        /// <remarks/>
        public string GTINCode;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://4solutions.co.au/")]
    public partial class DTOContact {
        
        /// <remarks/>
        public long ContactID;
        
        /// <remarks/>
        public string Phone;
        
        /// <remarks/>
        public string Fax;
        
        /// <remarks/>
        public string Mobile;
        
        /// <remarks/>
        public string Email;
        
        /// <remarks/>
        public string LastName;
        
        /// <remarks/>
        public string FirstName;
        
        /// <remarks/>
        public long CreatedByUserID;
        
        /// <remarks/>
        public long OldID;
    }
}
